GymProject/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace GymProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GymProject/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GymProject.Pages
{
    //[Authorize]
    //[AllowAnonymous]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

GymProject/Pages/LogOut.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace GymProject.Pages
{
    public class LogOutModel : PageModel
    {
        public async Task<IActionResult> OnGetAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme); 
            Response.Cookies.Delete("UserEmail");
            Response.Cookies.Delete("UserID");
            return RedirectToPage("/SignIn");
        }
    }
}

GymProject/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GymProject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GymProject/Pages/Product.cshtml.cs
using ClassLibrary.Classes.Item;
using ClassLibrary.Classes.User;
using Database.Repositories;
using InterfaceLibrary.IAlgorithmService;
using InterfaceLibrary.IRepositories;
using ManagerLibrary.Algorithm;
using ManagerLibrary.Algorithms;
using ManagerLibrary.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace GymProject.Pages
{
    public class ProductModel : PageModel
    {
        public List<Item> Supplements { get; set; }
        public List<Item> Programs { get; set; }
        public readonly ManagerLibrary.ManagerClasses.ItemManager itemManager;
        public string Sort { get; set; }
        public string Type { get; set; }
        public List<Item> MostBoughtItems { get; set; }
        public ISuggestionItemService suggestionItemService = new SuggestionItemsService(new UserRepository(), new ItemRepository(), new ShoppingRepository());
        public readonly ShoppingCartAlgorithms shoppingCartAlgorithms = new ShoppingCartAlgorithms(new UserRepository());


        public ProductModel()
        {
            itemManager = new ManagerLibrary.ManagerClasses.ItemManager(new ItemRepository());
        }


        public void OnGet()
        {

            var supplements = itemManager.GetSupplements();

            var programs = itemManager.GetPrograms();

            Supplements = supplements;

            Programs = programs;

            string userEmail = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;

            if (User.Identity.IsAuthenticated)
            {
                User user = shoppingCartAlgorithms.GetUserFromAuthentication(userEmail);

                List<Item> mostBoughtItems = suggestionItemService.GetProductSuggestions(user.Id);
                MostBoughtItems = mostBoughtItems;
            }
        }


        public void OnPost(string searchQuery, string sort)
        {
            if (!string.IsNullOrEmpty(searchQuery))
            {
                var searchResults = SearchForItems.SearchItems(searchQuery, itemManager.GetItems());
                Supplements = searchResults.supplements;
                Programs = searchResults.programs;
            }

            if (!string.IsNullOrEmpty(sort))
            {
                SortItems sortItems = new SortItems();
                List<Item> filteredSupplements = itemManager.GetSupplements();
                List<Item> filteredPrograms = itemManager.GetPrograms();
                if (sort == "lowToHigh")
                {
                    sortItems.SortByPriceAsc(filteredSupplements);
                    sortItems.SortByPriceAsc(filteredPrograms);
                }
                else if (sort == "highToLow")
                {
                    sortItems.SortByPriceDesc(filteredSupplements);
                    sortItems.SortByPriceDesc(filteredPrograms);
                }
                Supplements = filteredSupplements;
                Programs = filteredPrograms;
            }
        }
    }
}

GymProject/Pages/Profile.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GymProject.Pages
{
    public class ProfileModel : PageModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }

        public void OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                Email = User.FindFirstValue(ClaimTypes.Email);
            }
            else
            {
                if (Request.Cookies.TryGetValue("UserEmail", out string userEmail) &&
                    Request.Cookies.TryGetValue("UserID", out string userId))
                {
                    Email = userEmail;
                }
            }
        }
    }
}

GymProject/Pages/ShoppingCart.cshtml.cs
using ClassLibrary.Classes.Item;
using ClassLibrary.Classes.User;
using Database.Repositories;
using GymProject.SessionHelper;
using InterfaceLibrary.IAlgorithmService;
using ManagerLibrary.Algorithm;
using ManagerLibrary.ManagerClasses;
using ManagerLibrary.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Data;
using System.Security.Claims;

namespace GymProject.Pages
{
    [Authorize(Roles = "Admin, Customer")]
    public class ShoppingCart : PageModel
    {
        public readonly ShoppingCartManager shoppingCartManager = new ShoppingCartManager(new ShoppingRepository());
        public readonly ManagerLibrary.ManagerClasses.ItemManager itemManager = new ItemManager(new ItemRepository());
        public readonly ShoppingCartAlgorithms shoppingCartAlgorithms = new ShoppingCartAlgorithms(new UserRepository());
        public readonly UserManager userManager = new UserManager(new UserRepository());
        public readonly ISuggestionItemService suggestionItems = new SuggestionItems(new UserRepository(), new ItemRepository(), new ShoppingRepository());
        public List<Item> MyCart = new List<Item>();
        public List<Item> Items { get; set; }
        [BindProperty]
        public int Quantity { get; set; }
        [BindProperty]
        public int Id { get; set; }
        public double Total { get; set; }
        public string ErrorMessage { get; set; }

        public void OnGet()
        {
            MyCart = SessionHelper.SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            Total = shoppingCartAlgorithms.CalculateTotalPrice(MyCart);

            string userEmail = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            
            User user = shoppingCartAlgorithms.GetUserFromAuthentication(userEmail);

            var suggestedItems = suggestionItems.GetProductSuggestions(user.Id);

            Items = suggestedItems;
        }

        public IActionResult OnGetBuy(int id)
        {
            var product = itemManager.GetItemsById(id);
            var cart = SessionHelper.SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if(cart == null)
            {
                cart = new List<Item>();
                cart.Add(new Item()
                {
                    ItemId = product.ItemId,
                    ItemName = product.ItemName,
                    ItemQuantity = 1,
                    ItemPrice = product.ItemPrice
                });
                SessionHelper.SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                var index = ShoppingCartAlgorithms.ExistingItem(cart, id);
                if(index == -1)
                {
                    cart.Add(new Item
                    {
                        ItemId = product.ItemId,
                        ItemName = product.ItemName,
                        ItemQuantity =+ 1,
                        ItemPrice = product.ItemPrice
                    });
                }
                else
                {
                    var newQuantity = cart[index].ItemQuantity + 1;
                    cart[index].ItemQuantity = newQuantity;
                }
                SessionHelper.SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("Product");
        }

        public IActionResult OnPostAddToCart(int itemId)
        {
            var product = itemManager.GetItemsById(itemId);
            var cart = SessionHelper.SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");

            if (cart == null)
            {
                cart = new List<Item>();
            }

            var existingItem = cart.FirstOrDefault(item => item.ItemId == itemId);

            if (existingItem != null)
            {
                existingItem.ItemQuantity++;
            }
            else
            {
                cart.Add(new Item
                {
                    ItemId = product.ItemId,
                    ItemName = product.ItemName,
                    ItemQuantity = 1,
                    ItemPrice = product.ItemPrice
                });
            }

            SessionHelper.SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return RedirectToPage("ShoppingCart");
        }



        public IActionResult OnPostQuantity(string action)
        {
            if (Quantity >= 1)
            {
                List<Item> cart = SessionHelper.SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");

                Item itemToUpdate = cart.FirstOrDefault(item => item.ItemId == Id);

                if (itemToUpdate != null)
                {
                    if (action == "increase")
                    {
                        itemToUpdate.ItemQuantity++;
                    }
                    else if (action == "decrease")
                    {
                        if (itemToUpdate.ItemQuantity > 1)
                        {
                            itemToUpdate.ItemQuantity--;
                        }
                        else
                        {
                            cart.Remove(itemToUpdate);
                        }
                    }
                    SessionHelper.SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                }
                Total = shoppingCartAlgorithms.CalculateTotalPrice(cart);
            }
            return RedirectToPage("ShoppingCart");
        }

        public IActionResult OnPostPlaceOrder(string address)
        {
            try
            {
                string userEmail = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
                User user = shoppingCartAlgorithms.GetUserFromAuthentication(userEmail);
                MyCart = SessionHelper.SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                Total = shoppingCartAlgorithms.CalculateTotalPrice(MyCart);
                
                bool orderPlaced = shoppingCartManager.PlaceOrder(user, MyCart, address, Total);

                HttpContext.Session.Remove("cart");

                return RedirectToPage("Profile");
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return Page();
            }
        }
    }
}

GymProject/Pages/SignIn.cshtml.cs
using ClassLibrary.Classes.User;
using GymProject.ViewModels;
using ManagerLibrary.ManagerClasses;
using ManagerLibrary.Repositories;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;
using System.Security.Claims;

namespace GymProject.Pages
{
    public class SignInModel : PageModel
    {
        [BindProperty]
        public UserLoginModel LoggingUser { get; set; }

        public readonly ManagerLibrary.ManagerClasses.AuthenticationService authenticationService = new ManagerLibrary.ManagerClasses.AuthenticationService(new UserRepository());
        public string? ErrorMessage { get; set; }

        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Profile");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            try
            {
                if (string.IsNullOrEmpty(LoggingUser.Email) || string.IsNullOrEmpty(LoggingUser.Password))
                {
                    ErrorMessage = "Please enter your credentials";
                    return Page();
                }

                User? loggedUser = authenticationService.CheckLogin(LoggingUser.Email, LoggingUser.Password);

                List<Claim> claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.Email, loggedUser.Email));
                claims.Add(new Claim(ClaimTypes.Role, loggedUser.UserType.ToString()));

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties();

                if (!Request.Form.ContainsKey("RememberMe"))
                {
                    authProperties.ExpiresUtc = DateTime.UtcNow.AddMinutes(10);
                    authProperties.IsPersistent = false;
                }
                else
                {
                    authProperties.ExpiresUtc = DateTime.UtcNow.AddDays(5);
                    authProperties.IsPersistent = true;
                }

                HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);

                string? returnUrl = Request.Query["ReturnUrl"];
                if (string.IsNullOrEmpty(returnUrl))
                {
                    return RedirectToPage("/Profile");
                }
                return RedirectToPage(returnUrl);   
            }
            catch (Exception ex)
            {
                ErrorMessage = "Incorrect email or password";
                return Page();
            }

        }


    }
}

GymProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    <script src="https://kit.fontawesome.com/42b67a75fc.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    ViewData["Title"] = "Home page";
}

<body>
    <section id="title">
      <div class="row">
            <img class="img-david-laid" src="~/images/background-images/david-laid.png">
      </div>
    </section>

    <section id="features">
        <div class="row">
            <div class="feature-box col-lg-4">
                <a href="/Product#supplement">
                    <i class="icon fa-solid fa-dumbbell fa-4x"></i>
                    <h3>Certified Supplements</h3>
                    <p>Tested and working supplements</p>
                </a>
            </div>

            <div class="feature-box col-lg-4">
                <a href="/Product#program">
                    <i class="icon fa-solid fa-weight-hanging fa-4x"></i>
                    <h3>Programs for everyone</h3>
                    <p>The best programs out there</p>
                </a>
            </div>

            <div class="feature-box col-lg-4">
                <a href="/Product">
                    <i class="icon fa-solid fa-medal fa-4x"></i>
                    <h3>Elite products</h3>
                    <p>Recommended by a lot of athletes</p>
                </a>
            </div>
        </div>
    </section>


  <section id="testimonials">

    <div id="testimonial-carousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
            <h2 class="testimonial-text">Completely safe and working supplements, I mean just look at our biceps</h2>
            <em class ="TrenTwins testimonial-text">Tren Twins</em>
        </div>
        <div class="carousel-item">
            <h2 class="testimonial-text">Best programs</h2>
            <em class="Cbum testimonial-text">Cbum</em>
        </div>
      </div>
      <a class="carousel-control-prev" href="#testimonial-carousel" role="button" data-slide="prev"> 
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a> 
      <a class="carousel-control-next" href="#testimonial-carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

  </section>
</body>

GymProject/Pages/LogOut.cshtml
@page
@model GymProject.Pages.LogOutModel
@{
}

GymProject/Pages/Product.cshtml
@page
@using ClassLibrary.Classes.Item;
@model GymProject.Pages.ProductModel
@{
	ViewData["Title"] = "Product";
}
<div>
    <div class="row">
        <div class="col-md-3 order-2 order-md-1">
            <form method="post" asp-page-handler="search">
                <div class="input-group">
                    <input type="text" class="form-control" name="searchQuery" placeholder="Search...">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-7 order-1 order-md-2">
            <form method="post">
                <select name="sort">
                    <option selected disabled>Select filter</option>
                    <option value="lowToHigh">Low to High</option>
                    <option value="highToLow">High to Low</option>
                </select>
                <button type="submit">Apply Filter</button>
            </form>
        </div>
    </div>
</div>
<hr>
<div class="container">
    <div class="row justify-content-between">
        @{
            if (Model.Supplements == null || Model.Programs == null)
            {
                <p>No items found.</p>
            }
            else if (Model.Supplements.Count == 0 && Model.Programs.Count == 0)
            {
                <p>No items found.</p>
            }
            else
            {
                try
                {
                    if (Model.Supplements.Count > 0)
                    {
                        <h1>Supplements</h1>
                        foreach (var supplement in Model.Supplements)
                        {
                            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4" id="supplement">
                                <div class="card">
                                    <img class="card-img-top" src="~/images/products/trenbolone.jpg" alt="@supplement.ItemName">
                                    <div class="card-body">
                                        <h5 class="card-title">@supplement.ItemName</h5>
                                        <p class="card-text">@supplement.ItemDescription</p>
                                        <p class="card-text">@supplement.ItemPrice.ToString("$0.00")</p>
                                        <a asp-page="ShoppingCart" asp-page-handler="buy", asp-route-id ="@supplement.ItemId" class="btn btn-primary">Add to Cart</a>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    <hr style="border: 5px solid #000; margin: 20px 0;">
                    <h1>Programs</h1>
                    if (Model.Programs.Count > 0)
                    {
                        foreach (var program in Model.Programs)
                        {
                            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4" id="program">
                                <div class="card">
                                    <img class="card-img-top" src="~/images/ProgramGym.PNG" alt="@program.ItemName">
                                    <div class="card-body">
                                        <h5 class="card-title">@program.ItemName</h5>
                                        <p class="card-text">@program.ItemDescription</p>
                                        <p class="card-text">@program.ItemPrice.ToString("$0.00")</p>
                                        <a asp-page="ShoppingCart" asp-page-handler="buy" , asp-route-id="@program.ItemId" class="btn btn-primary">Add to Cart</a>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                }
                catch (Exception ex)
                {
                    <p>An error occurred while displaying items: @ex.Message</p>
                }
            }
        }
        <div class="col-12 row">
            <h1>Items you have bought a lot</h1>
            @if (Model.MostBoughtItems != null && Model.MostBoughtItems.Count > 0)
            {
                foreach (var item in Model.MostBoughtItems.GroupBy(i => i.ItemId).Select(g => g.First()).Take(3))
                {
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4" id="most-bought-item">
                        <div class="card">
                            <img class="card-img-top" src="~/images/products/trenbolone.jpg" alt="@item.ItemName">
                            <div class="card-body">
                                <h5 class="card-title">@item.ItemName</h5>
                                <p class="card-text">@item.ItemDescription</p>
                                <p class="card-text">@item.ItemPrice.ToString("$0.00")</p>
                                <a asp-page="ShoppingCart" asp-page-handler="buy" asp-route-id="@item.ItemId" class="btn btn-primary">Add to Cart</a>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <p>No items previously bought found</p>
            }
        </div>
    </div>
</div>

GymProject/Pages/Profile.cshtml
@page
@model GymProject.Pages.ProfileModel

<h1>Profile</h1>

@if (User.Identity.IsAuthenticated)
{
        <p>Email: @Model.Email</p>
        <div class="col-md-3 text-end">
            <a type="button" class="btn btn-outline-primary me-2" asp-page="Logout">Logout</a>
        </div>
}
else
{
        <p>You must be logged in to view your profile.</p>
}

GymProject/Pages/ShoppingCart.cshtml
@page
@model ShoppingCart
@{
    ViewData["Title"] = "Shopping cart";
}
<div class="shopping-cart-container container">
  <main>
        <div class="py-5 text-center">
			 <img class="d-block mx-auto mb-4" src="/images/logo_gym.png" alt="" width="72" height="57">
          <h2>Shopping Cart</h2>
        </div>

        <div class="row g-5">
          <div class="col-md-5 col-lg-4 order-md-last">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
              <span class="text-primary">Your cart</span>
            </h4>
            <ul class="list-group mb-3">
                    @if (Model.MyCart != null && Model.MyCart.Count > 0)
                        {
                    @foreach (var item in Model.MyCart)
                    {
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                            <div>
                                <h6 class="my-0">@item.ItemName</h6>
                                <form method="post" asp-page-handler="Quantity">
                                    <input type="hidden" name="Id" value="@item.ItemId" />
                                    <input type="hidden" name="Quantity" value="@item.ItemQuantity" />
                                    <button type="submit" name="action" value="decrease" class="btn btn-primary">-</button>
                                </form>
                                <span class="quantity">Quantity: @item.ItemQuantity</span>
                                    <form method="post" asp-page-handler="Quantity">
                                    <input type="hidden" name="Id" value="@item.ItemId" />
                                    <input type="hidden" name="Quantity" value="@item.ItemQuantity" />
                                    <button type="submit" name="action" value="increase" class="btn btn-primary">+</button>
                                </form>
                                <small class="text-muted" id="PricePerItem">Price per item: $@item.ItemPrice</small>
                            </div>
                            <span class="text-muted" id="ItemPrice">$@(item.ItemPrice * item.ItemQuantity)</span>
                        </li>
                    }
                }
                else
                {
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">Please Add Items</h6>
                        </div>
                    </li>
                }
                <li class="list-group-item d-flex justify-content-between">
                    <span >Total (USD)</span>
                    <strong>$@Model.Total.ToString()</strong>
                </li>
                @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                {
                    <div class="alert alert-danger">@Model.ErrorMessage</div>
                }
            </ul>
          </div>

          <div class="col-md-7 col-lg-8">
            <h4 class="mb-3">Billing information</h4>
                <form class="needs-validation" asp-page-handler="PlaceOrder" method="post">
              <div class="row g-3">
                <div class="col-12">
                  <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St" required="">
                  <div class="invalid-feedback">
                    Please enter your shipping address.
                  </div>
                </div>

                <hr class="my-4">

              <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
            </form>

                <hr class="my-4">

                @{
                    if (Model.Items == null || Model.Items.Count == 0)
                    {
                        <p>No items for suggestion.</p>
                    }
                    else
                    {
                        <h1>Suggested products</h1>
                        <h5>People that bought the same products as you also liked the following products:</h5>
                        <div class="row">
                            @foreach (var item in Model.Items.GroupBy(i => i.ItemId).Select(g => g.First()).Take(3))
                            {
                                <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
                                    <div class="card">
                                        <img class="card-img-top" src="~/images/products/trenbolone.jpg" alt="@item.ItemName">
                                        <div class="card-body">
                                            <h5 class="card-title">@item.ItemName</h5>
                                            <p class="card-text">@item.ItemPrice.ToString("$0.00")</p>
                                        </div>
                                        <form method="post" asp-page-handler="AddToCart">
                                            <input type="hidden" name="itemId" value="@item.ItemId" />
                                            <button type="submit" class="btn btn-primary">Add to Cart</button>
                                        </form>
                                    </div>
                                </div>
                            }
                        </div>
                    }
                }
          </div>
        </div>
  </main>
</div>

GymProject/Pages/SignIn.cshtml
@page
@model GymProject.Pages.SignInModel
@{
    ViewData["Title"] = "Sign in";
}

    <main class="form-signin w-100 m-auto">
        <form method="post">
            <img class="mb-4" src="~/images/logo_gym.png" alt="" width="72" height="57">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

            <div class="form-floating">
                <input asp-for="LoggingUser.Email" type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
                <input asp-for="LoggingUser.Password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>
            @if (!string.IsNullOrEmpty(Model.ErrorMessage))
            {
                <div class="alert alert-danger" role="alert">
                    @Model.ErrorMessage
                </div>
            }
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" name="RememberMe"> Remember me
                </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            <div class="text-center">
                <p>Don't have an account yet? <a href="/SignUp" style="color: blue;">Sign up</a></p>
            </div>
        </form>
    </main>